"""Ensure there can only be one char with a name

Revision ID: 00fdf6a46afe
Revises: 4f517b4852bc
Create Date: 2023-07-14 14:01:00.608392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00fdf6a46afe'
down_revision = '4f517b4852bc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Character', schema=None) as batch_op:
        batch_op.create_unique_constraint("ux_char_name", ['name'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Character', schema=None) as batch_op:
        batch_op.drop_constraint("ux_char_name", type_='unique')

    # ### end Alembic commands ###
