"""Add default empty str to Character.notes

Revision ID: 06d783218413
Revises: 00fdf6a46afe
Create Date: 2023-07-14 14:14:05.558975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06d783218413'
down_revision = '00fdf6a46afe'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
