"""Connect SceneStatus to Scene

Revision ID: 28f0f6ebf70c
Revises: 82373bd65da7
Create Date: 2023-07-21 10:52:00.722319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28f0f6ebf70c'
down_revision = '82373bd65da7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Scene', schema=None) as batch_op:
        batch_op.create_foreign_key('FK_Scene2SceneStatus', 'SceneStatus', ['scene_status_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Scene', schema=None) as batch_op:
        batch_op.drop_constraint('FK_Scene2SceneStatus', type_='foreignkey')

    # ### end Alembic commands ###
