"""add color field to SceneStatus

Revision ID: 49f75e0bca5d
Revises: 28f0f6ebf70c
Create Date: 2023-07-21 14:51:14.925588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49f75e0bca5d'
down_revision = '28f0f6ebf70c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('SceneStatus', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('SceneStatus', schema=None) as batch_op:
        batch_op.drop_column('color')

    # ### end Alembic commands ###
