"""Redo characters as many to many scenes and many to one book

Revision ID: 4f517b4852bc
Revises: e43961f1a249
Create Date: 2023-07-14 13:48:51.050624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f517b4852bc'
down_revision = 'e43961f1a249'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('book_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key("FK_Book2Scenes", 'Book', ['book_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Character', schema=None) as batch_op:
        batch_op.drop_constraint("FK_Book2Scenes", type_='foreignkey')
        batch_op.drop_column('book_id')

    # ### end Alembic commands ###
